CREATE TABLE llx_mahnwesen_attempt (
    rowid INTEGER AUTO_INCREMENT PRIMARY KEY,
    entity INTEGER DEFAULT 1 NOT NULL,
    fk_case INTEGER NOT NULL,
    fk_facture INTEGER NOT NULL,
    level INTEGER NOT NULL,
    mode VARCHAR(32) DEFAULT 'manual' NOT NULL,
    status VARCHAR(32) DEFAULT 'reserved' NOT NULL,
    recipient VARCHAR(255) NOT NULL,
    fk_socpeople INTEGER,
    sender VARCHAR(255) NOT NULL,
    cc TEXT,
    bcc TEXT,
    subject VARCHAR(255) NOT NULL,
    body_html TEXT,
    amount_invoice DOUBLE(24,8) DEFAULT 0 NOT NULL,
    amount_fee DOUBLE(24,8) DEFAULT 0 NOT NULL,
    amount_total DOUBLE(24,8) DEFAULT 0 NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    fk_email_template INTEGER,
    template_lang VARCHAR(16),
    pdf_path TEXT,
    pdf_sha256 VARCHAR(64),
    invoice_pdf_path TEXT,
    invoice_pdf_sha256 VARCHAR(64),
    mail_message_id VARCHAR(255),
    error_message TEXT,
    reserved_at DATETIME NOT NULL,
    sent_at DATETIME,
    resolved_at DATETIME,
    fk_user_create INTEGER,
    fk_user_resolve INTEGER,
    tms TIMESTAMP
) ENGINE=innodb;
