<?php
/* Auto-split method trait for maintainable source files. */
trait DunningNoticeServiceMethods2
{
    public function getRecipientOptions($invoice){$options=array();$seen=array();$sql='SELECT sp.rowid,sp.firstname,sp.lastname,sp.email FROM '.MAIN_DB_PREFIX.'element_contact ec INNER JOIN '.MAIN_DB_PREFIX.'c_type_contact tc ON tc.rowid=ec.fk_c_type_contact INNER JOIN '.MAIN_DB_PREFIX."socpeople sp ON sp.rowid=ec.fk_socpeople WHERE ec.element_id=".((int)$invoice->id)." AND tc.element='facture' AND tc.source='external' AND tc.code='BILLING' AND sp.email IS NOT NULL AND sp.email<>'' ORDER BY sp.lastname,sp.firstname,sp.rowid";$resql=$this->db->query($sql);if($resql){while($obj=$this->db->fetch_object($resql)){$email=trim((string)$obj->email);if(!filter_var($email,FILTER_VALIDATE_EMAIL))continue;$key=strtolower($email);if(isset($seen[$key]))continue;$name=trim((string)$obj->firstname.' '.(string)$obj->lastname);$options[]=array('email'=>$email,'label'=>$name!==''?$name.' <'.$email.'>':$email,'source'=>'billing_contact');$seen[$key]=1;}$this->db->free($resql);}else{$this->errors[]='Recipient contact lookup failed: '.$this->db->lasterror();}if(empty($invoice->thirdparty))$invoice->fetch_thirdparty();if(!empty($invoice->thirdparty)&&!empty($invoice->thirdparty->email)){$email=trim((string)$invoice->thirdparty->email);$key=strtolower($email);if(filter_var($email,FILTER_VALIDATE_EMAIL)&&!isset($seen[$key]))$options[]=array('email'=>$email,'label'=>(string)$invoice->thirdparty->name.' <'.$email.'>','source'=>'thirdparty');}return $options;}
    public function getAutomaticRecipient($invoice,$policy='single_billing'){$options=$this->getRecipientOptions($invoice);$billing=array();$fallback='';foreach($options as $option){if($option['source']==='billing_contact')$billing[]=$option['email'];elseif($option['source']==='thirdparty'&&$fallback==='')$fallback=$option['email'];}if($policy==='first_billing')return !empty($billing)?(string)$billing[0]:$fallback;if(count($billing)===1)return (string)$billing[0];if(count($billing)>1)return '';return $fallback;}
    public function isManualSendEnabled(){return getDolGlobalInt('MAHNWESEN_MANUAL_SEND_ENABLED',0)>0;}
    public function isAutomaticSendEnabled(){return getDolGlobalInt('MAHNWESEN_AUTO_SEND_ENABLED',0)>0;}
    public function getFromEmail($templateFrom=''){global $mysoc;$email=trim((string)$templateFrom);if($email==='')$email=trim(getDolGlobalString('MAHNWESEN_FROM_EMAIL'));if($email==='')$email=trim(getDolGlobalString('MAIN_MAIL_EMAIL_FROM'));if($email===''&&is_object($mysoc)&&!empty($mysoc->email))$email=trim((string)$mysoc->email);if(preg_match('/<([^<>]+)>/',$email,$m))$email=trim($m[1]);return filter_var($email,FILTER_VALIDATE_EMAIL)?$email:'';}
    public function getSenderOptions($user=null,$preferred=''){global $mysoc;$options=array();$seen=array();$effective=$this->getFromEmail($preferred);if($effective!==''){$label=(is_object($mysoc)&&!empty($mysoc->name))?(string)$mysoc->name.' <'.$effective.'>':$effective;$options[]=array('email'=>$effective,'label'=>$label,'source'=>'default');$seen[strtolower($effective)]=0;}$sql='SELECT rowid,label,email,private FROM '.MAIN_DB_PREFIX.'c_email_senderprofile WHERE active=1 AND entity IN ('.getEntity('emailsenderprofile').')';$uid=(is_object($user)&&isset($user->id))?(int)$user->id:0;$sql.=' AND (private=0'.($uid>0?' OR private='.$uid:'').') ORDER BY position ASC,label ASC,rowid ASC';$resql=$this->db->query($sql);if(!$resql){dol_syslog(__METHOD__.' Unable to load email sender profiles: '.$this->db->lasterror(),LOG_WARNING);return $options;}while($obj=$this->db->fetch_object($resql)){$email=trim((string)$obj->email);if(!filter_var($email,FILTER_VALIDATE_EMAIL))continue;$key=strtolower($email);$label=trim((string)$obj->label);if(isset($seen[$key])){$idx=(int)$seen[$key];if($label!==''&&isset($options[$idx])){$options[$idx]['label']=$label.' <'.$email.'>';$options[$idx]['source']='profile';}continue;}$options[]=array('email'=>$email,'label'=>$label!==''?$label.' <'.$email.'>':$email,'source'=>'profile');$seen[$key]=count($options)-1;}$this->db->free($resql);return $options;}
    public function renderTemplate($text,$invoice,$case,$level,$lang=''){global $conf,$langs,$mysoc;if(empty($invoice->thirdparty))$invoice->fetch_thirdparty();if($lang==='')$lang=is_object($langs)?$langs->defaultlang:'de_DE';$outputlangs=new Translate('',$conf);$outputlangs->setDefaultLang($lang);$outputlangs->loadLangs(array('main','bills','companies','mahnwesen@mahnwesen'));$breakdown=$this->manager->getAmountBreakdown($invoice,$case,$level);$open=$this->formatMoney($breakdown['invoice'],$outputlangs);$fee=$this->formatMoney($breakdown['fee'],$outputlangs);$total=$this->formatMoney($breakdown['total'],$outputlangs);$classLabel=$outputlangs->trans($this->manager->getCustomerClassLabelKey($breakdown['classification']['class']));$stage=$outputlangs->trans($this->manager->getStageLabelKey((int)$level));$next=(!empty($case['next_action_at'])&&empty($case['paused']))?dol_print_date($this->db->jdate($case['next_action_at']),'day','tzserver',$outputlangs):'';$feeParagraph=$breakdown['fee']>0.000001?((stripos($lang,'de')===0)?'Zusätzlich werden Mahn-/Betreibungskosten in Höhe von <strong>'.$fee.'</strong> berücksichtigt.':'In addition, dunning/collection costs of <strong>'.$fee.'</strong> are included.') : '';$formmail=new FormMail($this->db);$formmail->setSubstitFromObject($invoice,$outputlangs);$formmail->substit['__MAHNWESEN_STAGE__']=$stage;$formmail->substit['__MAHNWESEN_OPEN_AMOUNT__']=$open;$formmail->substit['__MAHNWESEN_FEE__']=$fee;$formmail->substit['__MAHNWESEN_TOTAL__']=$total;$formmail->substit['__MAHNWESEN_CUSTOMER_CLASS__']=$classLabel;$formmail->substit['__MAHNWESEN_NEXT_STAGE_DATE__']=$next;$formmail->substit['__MAHNWESEN_FEE_PARAGRAPH__']=$feeParagraph;$rendered=make_substitutions((string)$text,$formmail->substit,$outputlangs);return strtr($rendered,array('{INVOICE_REF}'=>(string)$invoice->ref,'{CUSTOMER_NAME}'=>!empty($invoice->thirdparty)?(string)$invoice->thirdparty->name:'','{INVOICE_DATE}'=>dol_print_date($invoice->date,'day','tzserver',$outputlangs),'{DUE_DATE}'=>dol_print_date($invoice->date_lim_reglement,'day','tzserver',$outputlangs),'{OPEN_AMOUNT}'=>$open,'{DUNNING_FEE}'=>$fee,'{DUNNING_TOTAL}'=>$total,'{CUSTOMER_CLASS}'=>$classLabel,'{DUNNING_STAGE}'=>$stage,'{TODAY}'=>dol_print_date(dol_now(),'day','tzserver',$outputlangs),'{COMPANY_NAME}'=>is_object($mysoc)?(string)$mysoc->name:'','{NEXT_STAGE_DATE}'=>$next,'{FEE_PARAGRAPH}'=>$feeParagraph));}
    public function getInvoicePdfPath($invoice){global $conf;$entity=!empty($invoice->entity)?(int)$invoice->entity:(int)$conf->entity;$root=isset($conf->facture->multidir_output[$entity])?$conf->facture->multidir_output[$entity]:(!empty($conf->facture->dir_output)?$conf->facture->dir_output:'');if($root==='')return '';if(!empty($invoice->last_main_doc)){$path=rtrim($root,'/').'/'.ltrim((string)$invoice->last_main_doc,'/');if(is_file($path)&&is_readable($path))return $path;}$ref=dol_sanitizeFileName($invoice->ref);$fallback=rtrim($root,'/').'/'.$ref.'/'.$ref.'.pdf';return is_file($fallback)&&is_readable($fallback)?$fallback:'';}
    public function getExistingFinalPdfInfo($invoice,$level){$root=$this->getInvoiceDocumentRoot($invoice);if($root==='')return false;$safeRef=dol_sanitizeFileName($invoice->ref);$stagePart=$this->getStageFilenamePart((int)$level);$invoicePdfPath=$this->getInvoicePdfPath($invoice);$dir=$invoicePdfPath!==''?dirname($invoicePdfPath):rtrim($root,'/').'/'.$safeRef;$filename=$safeRef.'_'.$stagePart.'.pdf';$fullpath=$dir.'/'.$filename;if(!is_file($fullpath)||!is_readable($fullpath)||filesize($fullpath)<=0)return false;$relativeDir=ltrim(str_replace('\\','/',substr($dir,strlen(rtrim($root,'/')))),'/');$relative=($relativeDir!==''?$relativeDir.'/':'').$filename;return array('fullpath'=>$fullpath,'relative'=>$relative,'filename'=>$filename,'modulepart'=>'invoice','preview'=>0);}
    public function getFinalPdfFilename($invoice,$level){return dol_sanitizeFileName($invoice->ref).'_'.$this->getStageFilenamePart((int)$level).'.pdf';}
    protected function getStageFilenamePart($level){switch((int)$level){case 1:return'Zahlungserinnerung';case 2:return'1.Mahnung';case 3:return'2.Mahnung';case 4:return'3.Mahnung';default:return'Mahnung';}}
    protected function getInvoiceDocumentRoot($invoice){global $conf;$entity=!empty($invoice->entity)?(int)$invoice->entity:(int)$conf->entity;if(!empty($conf->facture->multidir_output[$entity]))return rtrim((string)$conf->facture->multidir_output[$entity],'/');if(!empty($conf->facture->dir_output))return rtrim((string)$conf->facture->dir_output,'/');return '';}
    protected function prepareBodyForPdf($body){$body=(string)$body;$marker='<!--MAHNWESEN_PDF_END-->';$pos=stripos($body,$marker);if($pos!==false)$body=substr($body,0,$pos);$body=preg_replace('~<(script|style)\b[^>]*>.*?</\1>~is','',$body);$body=preg_replace('~<img\b[^>]*>~is','',$body);return trim($body);}
}
